CREATE TABLE SITE(
	ID_SITE INT PRIMARY KEY,
	NOME_SITE TEXT UNIQUE
);

CREATE INDEX idx_site on SITE(ID_SITE);


CREATE TABLE NOTICIA(
	ID_NOTICIA INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_SITE INT,
	TITULO_NOTICIA TEXT,
	URL_NOTICIA TEXT,
	URL_IMG TEXT,
	DESCRICAO TEXT,
	DATA_PUBLICACAO TEXT,
	CATEGORIA TEXT,
	FOREIGN KEY (ID_SITE) REFERENCES SITE(ID_SITE)
);
CREATE INDEX idx_noticia on NOTICIA(ID_NOTICIA);

ALTER TABLE NOTICIA 

INSERT INTO SITE ('ID_SITE', 'NOME_SITE')    
VALUES (1, 'GLOBO')

SELECT * 
FROM SITE ;

SELECT *
FROM NOTICIA
ORDER BY ID_SITE ;

TRUNCATE TABLE NOTICIA;